// Generated by gencpp from file serial_manager/Param.msg
// DO NOT EDIT!


#ifndef SERIAL_MANAGER_MESSAGE_PARAM_H
#define SERIAL_MANAGER_MESSAGE_PARAM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_manager
{
template <class ContainerAllocator>
struct Param_
{
  typedef Param_<ContainerAllocator> Type;

  Param_()
    : header(0)
    , param(0.0)  {
    }
  Param_(const ContainerAllocator& _alloc)
    : header(0)
    , param(0.0)  {
    }



   typedef uint8_t _header_type;
  _header_type header;

   typedef float _param_type;
  _param_type param;




  typedef boost::shared_ptr< ::serial_manager::Param_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_manager::Param_<ContainerAllocator> const> ConstPtr;

}; // struct Param_

typedef ::serial_manager::Param_<std::allocator<void> > Param;

typedef boost::shared_ptr< ::serial_manager::Param > ParamPtr;
typedef boost::shared_ptr< ::serial_manager::Param const> ParamConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_manager::Param_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_manager::Param_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace serial_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'serial_manager': ['/home/stefano/Progetto_Drone/Odroid_ArCaRa/NapoDrone_ws/src/SerialManager/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::serial_manager::Param_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_manager::Param_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_manager::Param_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_manager::Param_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_manager::Param_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_manager::Param_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_manager::Param_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4ccd10a5f71453ae65c8aa51332c817e";
  }

  static const char* value(const ::serial_manager::Param_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4ccd10a5f71453aeULL;
  static const uint64_t static_value2 = 0x65c8aa51332c817eULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_manager::Param_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_manager/Param";
  }

  static const char* value(const ::serial_manager::Param_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_manager::Param_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 header\n\
float32 param\n\
";
  }

  static const char* value(const ::serial_manager::Param_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_manager::Param_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.param);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Param_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_manager::Param_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_manager::Param_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.header);
    s << indent << "param: ";
    Printer<float>::stream(s, indent + "  ", v.param);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_MANAGER_MESSAGE_PARAM_H
